### ISSUE TITLE
AttributeError: type object 'KfPGroupProd' has no attribute 'INPUT_TYPES'

### ISSUE THREAD

**Issue by toyxyz** [dmarx/ComfyUI-Keyframed#27]
It doesn't break anything. Does anyone else have the same error?

FETCH DATA from: C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
[ERROR] An error occurred while retrieving information for the 'KfPGroupProd' node.
Traceback (most recent call last):
File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\server.py", line 418, in get_object_info
out[x] = node_info(x)
^^^^^^^^^^^^
File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\server.py", line 396, in node_info
info['input'] = obj_class.INPUT_TYPES()
^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'KfPGroupProd' has no attribute 'INPUT_TYPES'

**Comment by ricardofeynman** [comment]
Same on linux

FETCH DATA from: /meh/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json
[ERROR] An error occurred while retrieving information for the 'KfPGroupProd' node.
Traceback (most recent call last):
  File "/meh/ComfyUI/server.py", line 418, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "/meh/ComfyUI/server.py", line 396, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'KfPGroupProd' has no attribute 'INPUT_TYPES'

**Comment by dmarx** [comment]
KfPGroupProd is a node i was playing with but i couldn't get to work right. i guess to remind myself or something i left the class in but left the body as just "pass". Comfy tries to load the node... because i'm an idiot and left this node in the list of nodes that gets exported. but yeah so when comfy tries to load the node, it assumes that the node has an INPUT_TYPES attribute. 

just to explain what's going on and why it's not breaking anything.

**Comment by dmarx** [comment]
fixed with 253303c1d26ee5a5580a549a7fb9369961af4066
